project:
  type: website

website:
  title: "Robert Granger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/about.qmd
        text: About
      - href: research/research.qmd
        text: Research
      - href: teaching/teaching.qmd
        text: Teaching
      - href: apps/apps.qmd
        text: Apps

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: false